version: '3.1'
services:
  provoviz:
    image: provoviz
    build: provoviz
    ports:
      - 5000:5000
  zookeeper:
    image: zookeeper:3.5.6
    restart: always
    ports:
      - 2181:2181
  kafka:
    image: wurstmeister/kafka:2.12-2.4.0
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_LOG_DIRS: /kafka
      KAFKA_BROKER_ID: 1
      KAFKA_CREATE_TOPICS: repo:1:1
      HOSTNAME_COMMAND: "/sbin/ip route | awk '/default/ { print $$3 }'"
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_LOG_RETENTION_HOURS: "168"
      KAFKA_LOG_RETENTION_BYTES: "100000000"
      KAFKA_ZOOKEEPER_CONNECT:  zookeeper:2181